server:
  port: 8085
spring:
  application:
    name: raffle
  config:
    activate:
      on-profile: local
  datasource:
      url: jdbc:mysql://localhost:3306/raffle?useUnicode=yes&characterEncoding=UTF-8&rewriteBatchedStatements=true
      driver-class-name: com.mysql.cj.jdbc.Driver
      hikari:
        maximum-pool-size: 10
        max-lifetime: 30000
        connection-timeout: 3000
      username: raffle
      password: 1234
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  data:
    redis:
      host: localhost
      port: 6380